/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libusb_LibUSBJNI */

#ifndef _Included_org_libusb_LibUSBJNI
#define _Included_org_libusb_LibUSBJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libusb_LibUSBJNI
 * Method:    usb_jni_demo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libusb_LibUSBJNI_usb_1jni_1demo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
